server:
  port: 8088
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smartravel
  mvc:
      static-path-pattern: /static/**
  freemarker:
      cache: false
      suffix: .ftl
  #返回时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
