-- 酒店
CREATE TABLE t_user
(
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键id',
  username VARCHAR(32) NOT NULL COMMENT '用户名',
  password VARCHAR(32) NOT NULL COMMENT '密码',
  mobile VARCHAR(11) NOT NULL COMMENT '密码',
  member_level VARCHAR(32) NOT NULL COMMENT '会员等级',
  point INT NOT NULL COMMENT '会员积分',
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间',
  last_login_time DATETIME COMMENT '最近登录时间'
) COMMENT '用户表';

-- 酒店
CREATE TABLE t_hotel
(
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键id',
  provence VARCHAR(32) NOT NULL COMMENT '省份',
  city VARCHAR(32) NOT NULL COMMENT '城市',
  street VARCHAR(32) NOT NULL COMMENT '街道',
  name VARCHAR(32) NOT NULL COMMENT '酒店名称',
  english_name VARCHAR(32) NOT NULL COMMENT '酒店英文名称',
  type VARCHAR(32) NOT NULL COMMENT '酒店类型',
  star INT NOT NULL COMMENT '酒店评级',
  near_by_business INT NOT NULL COMMENT '附近商圈',
  tags INT NOT NULL COMMENT '酒店标签',
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间'
) COMMENT '用户表';

-- 酒店房间
CREATE TABLE t_hotel_room
(
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键id',
  hotel_id BIGINT NOT NULL COMMENT '酒店id',
  type VARCHAR(32) NOT NULL COMMENT '房间类型',
  size VARCHAR(32) NOT NULL COMMENT '容纳人数',
  floor INT NOT NULL COMMENT '楼层',
  bed_size DOUBLE NOT NULL COMMENT '床位尺寸',
  has_breakfast BIGINT NOT NULL COMMENT '是否含早餐 0否 1是',
  net_type INT NOT NULL COMMENT '网络类型',
  day_avg_price DOUBLE NOT NULL COMMENT '日均价',
  is_cancel DOUBLE NOT NULL COMMENT '是否可以取消 0否 1是',
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间'
) COMMENT '酒店房间表';

-- 旅游套餐
CREATE TABLE t_scenic_spot
(
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键id',
  country VARCHAR(32) NOT NULL COMMENT '国家',
  provence VARCHAR(32) NOT NULL COMMENT '省份',
  city VARCHAR(32) NOT NULL COMMENT '城市',
  street VARCHAR(32) NOT NULL COMMENT '街道',
  name VARCHAR(32) NOT NULL COMMENT '景区名称',
  english_name VARCHAR(32) NOT NULL COMMENT '景区英文名称',
  star INT NOT NULL COMMENT '景区评级',
  type VARCHAR(32) NOT NULL COMMENT '景区类型',
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间'
) COMMENT '旅游景区表';

-- 旅游套餐
CREATE TABLE t_scenic_spot_plans
(
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键id',
  scenic_spot BIGINT NOT NULL COMMENT '景点id',
  type BIGINT NOT NULL COMMENT '套餐类型',
  days INT NOT NULL COMMENT '行程天数',
  transport_mode INT NOT NULL COMMENT '往返交通方式',
  start_place VARCHAR(32) NOT NULL COMMENT '出发地',
  destination VARCHAR(32) NOT NULL COMMENT '目的地',
  original_price BIGINT NOT NULL COMMENT '套餐原价',
  price BIGINT NOT NULL COMMENT '套餐现价',
  travel_time DATETIME NOT NULL COMMENT '出发日期',
  travel_plan DATETIME NOT NULL COMMENT '行程概要',
  travel_desc VARCHAR(256) NOT NULL COMMENT '套餐简介',
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间'
) COMMENT '旅游套餐表';
